### ISSUE TITLE
http: panic serving [::1]:61264: runtime error

### ISSUE THREAD

**Issue by istemi** [c1982/awsdtc#1]
Application is not responding and showing the following error from the console:

```
2021/05/17 06:39:58 http: panic serving [::1]:61264: runtime error: invalid memory address or nil pointer dereference
goroutine 6 [running]:
net/http.(*conn).serve.func1(0xc0000a7540)
	/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x15589a0, 0x198fc40)
	/usr/local/go/src/runtime/panic.go:971 +0x499
text/template.errRecover(0xc000064ac0)
	/usr/local/go/src/text/template/exec.go:163 +0x1b2
panic(0x15589a0, 0x198fc40)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
text/template.(*Template).execute(0x0, 0x1706e20, 0xc0002901c0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:217 +0x180
text/template.(*Template).Execute(...)
	/usr/local/go/src/text/template/exec.go:203
main.RunPage.func2(0x170d220, 0xc0002901c0, 0xc000280300)
	/Users/oguzhan/go/src/awsdtc/web.go:59 +0x74
net/http.HandlerFunc.ServeHTTP(0xc000021900, 0x170d220, 0xc0002901c0, 0xc000280300)
	/usr/local/go/src/net/http/server.go:2069 +0x44
net/http.(*ServeMux).ServeHTTP(0x199f160, 0x170d220, 0xc0002901c0, 0xc000280300)
	/usr/local/go/src/net/http/server.go:2448 +0x1ad
net/http.serverHandler.ServeHTTP(0xc000290000, 0x170d220, 0xc0002901c0, 0xc000280300)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0000a7540, 0x170e040, 0xc000112000)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b
```

**Comment by c1982** [comment]
Thanks. I fixed this version https://github.com/c1982/awsdtc/releases/tag/v1.0.4
